packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  vue-demi: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - unrs-resolver
  - vue-demi
