packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.4.4'
  - '@storybook/addon-docs@10.4.4'
  - '@storybook/addon-links@10.4.4'
  - '@storybook/addon-themes@10.4.4'
  - '@storybook/addon-vitest@10.4.4'
  - '@storybook/builder-vite@10.4.4'
  - '@storybook/cli@10.4.4'
  - '@storybook/codemod@10.4.4'
  - '@storybook/csf-plugin@10.4.4'
  - '@storybook/react-dom-shim@10.4.4'
  - '@storybook/vue3-vite@10.4.4'
  - '@storybook/vue3@10.4.4'
  - baseline-browser-mapping@2.10.36
  - create-storybook@10.4.4
  - storybook@10.4.4
  - '@volverjs/style@0.1.24-beta.4'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - unrs-resolver
  - vue-demi
