name: Check pipeline

on:
    # Run on pull request
    pull_request:
        branches: [main, develop]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
    pull-requests: read

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    analysis:
        uses: ./.github/workflows/sonarcloud.yml
        secrets: inherit

    build:
        needs: analysis
        uses: ./.github/workflows/build.yml

    # Vercel deploy for storybook testing
    vercel-deploy:
        needs: build
        uses: ./.github/workflows/vercel-deploy.yml
        secrets: inherit

    test:
        needs: vercel-deploy
        uses: ./.github/workflows/test.yml
