name: Check pipeline

on:
    # Run on pull request
    pull_request:
        branches: [main, develop]
    push:
        branches:
            - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    analysis:
        uses: ./.github/workflows/sonarcloud.yml
        secrets: inherit

    styleguide:
        needs: analysis
        uses: ./.github/workflows/styleguide.yml
        secrets: inherit
        with:
            testEnv: true

    test:
        needs: styleguide
        uses: ./.github/workflows/test.yml
        with:
            testEnv: true

    build:
        needs: test
        uses: ./.github/workflows/build.yml
