name: Main pipeline

on:
    # Runs on release publish
    release:
        types: [published]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
    pull-requests: read

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    analysis:
        uses: ./.github/workflows/sonarcloud.yml
        secrets: inherit

    styleguide:
        needs: analysis
        uses: ./.github/workflows/styleguide.yml

    test:
        needs: styleguide
        uses: ./.github/workflows/test.yml

    build:
        needs: test
        uses: ./.github/workflows/build.yml

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
