name: Main pipeline

on:
    # Runs on release publish
    release:
        types: [published]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
    pull-requests: read

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # Sonarcloud analysis
    analysis:
        uses: ./.github/workflows/sonarcloud.yml
        secrets: inherit

    # Vercel deploy for storybook test
    vercel-deploy:
        uses: ./.github/workflows/vercel-deploy.yml
        secrets: inherit

    # Styleguide test on Vercel env
    test:
        needs: vercel-deploy
        uses: ./.github/workflows/test.yml

    # Publish styleguide to GitHub Pages
    styleguide:
        needs: test
        uses: ./.github/workflows/styleguide.yml

    # Build package
    build:
        uses: ./.github/workflows/build.yml

    # Publish package to NPM
    publish-npm:
        needs: [build, styleguide, test, analysis]
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    # Publish package to GPR
    publish-gpr:
        needs: [build, styleguide, test, analysis]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: package
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm publish $(ls *.tgz) --access=public --tag ${{ github.event.release.prerelease && 'next' || 'latest'}}
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
