name: Auto-merge PR
on:
    check_suite:
        types:
            - completed

permissions:
    pull-requests: write
    contents: write

jobs:
    merge-pr:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'depfu[bot]' }}
        steps:
            # - name: Dependabot metadata
            #   id: metadata
            #   uses: dependabot/fetch-metadata@v1
            #   with:
            #       github-token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --auto --merge --squash "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            # - name: Approve patch and minor updates
            #   if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
            #   run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
            #   env:
            #       PR_URL: ${{github.event.pull_request.html_url}}
            #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
