name: Check PR

on:
    # Run on pull request
    pull_request:
        branches: [main, develop]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: read

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # Sonarcloud analysis
    analysis:
        uses: ./.github/workflows/sonarcloud.yml
        secrets: inherit

    # CI
    build:
        needs: analysis
        uses: ./.github/workflows/build.yml

    # Vercel deploy env for storybook test
    vercel-deploy:
        needs: build
        uses: ./.github/workflows/vercel-deploy.yml
        secrets: inherit

    # Storybook test on vercel env
    vercel-test:
        needs: vercel-deploy
        uses: ./.github/workflows/test.yml

    # Trigger depfu merge
    trigger-automerge:
        needs: vercel-test
        uses: ./.github/workflows/pr-depfu-merge.yml
