name: Merge Depfu PR
on:
    # Triggered by pr-check-suite.yml
    # on check_suite:completed with positive result
    repository_dispatch:
        types: [checks-complete]

permissions:
    pull-requests: write
    contents: write

jobs:
    merge-pr:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'depfu[bot]' }}
        steps:
            - name: Squash PR
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
