name: Test library

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: pnpm/action-setup@v6

            - name: Use Node.js 24
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Bump version with release tag name
              if: ${{ github.event_name == 'release' }}
              run: pnpm version --no-git-tag-version ${{ github.event.release.tag_name }}

            - name: Build styleguide
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096'
              run: pnpm styleguide

            - name: Setup GitHub Pages
              uses: actions/configure-pages@v6

            - name: Upload styleguide
              uses: actions/upload-pages-artifact@v4
              with:
                  name: 'github-pages'
                  path: './storybook-static'
