name: Test library

on:
    workflow_call:
        inputs:
            testEnv:
                default: false
                required: false
                type: boolean

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
            - name: Bump version with release tag name
              run: pnpm version --no-git-tag-version ${{ github.event.release.tag_name }}
            - name: Build styleguide
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096'
              run: pnpm styleguide

            # if not testEnv -> deploy on github pages
            - name: Setup GitHub Pages
              if: ${{ !inputs.testEnv }}
              uses: actions/configure-pages@v2
            - name: Upload styleguide
              if: ${{ !inputs.testEnv }}
              uses: actions/upload-pages-artifact@v1
              with:
                  path: './storybook-static'

    # if testEnv -> Vercel deploy for PR testing
    vercel-deploy:
        if: ${{ inputs.testEnv }}
        uses: ./.github/workflows/vercel-deploy.yml
        secrets: inherit

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        if: ${{ !inputs.testEnv }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
